build:
  script:
    - source /root/.nvm/nvm.sh > /dev/null 2>&1
    - nvm use stable
    - rbenv global 2.2.2
    - bundle install --deployment --quiet --path /cache
    - bundle exec middleman build
    - bundle exec s3_website push
  only:
    - master
